---
title: "PA1_template"
author: "kwan lee"
date: "February 25, 2017"
output:
 # html_document: default
  md_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# download the data
```{r cars}
summary(cars)
```

```
temp <- tempfile()
download.file("https://d396qusza40orc.cloudfront.net/repdata%2Fdata%2Factivity.zip", temp, mode="wb", method="curl")
```

# Loading and preprocessing the data
```
unzip(temp, "activity.csv")
activityData <- read.table("activity.csv", sep=",", header = T)
totalSteps <- aggregate(steps ~ date, data = activityData, sum, na.rm = T)

```

# What is mean total number of steps taken per day?
```
# 1. Make a histogram of the total number of steps taken each day
hist(totalSteps$steps, 
     main = "Histogram of Total Steps taken per day",
     xlab = "Total Steps taken per day", 
     cex.axis = 1, cex.lab = 1)

# 2. Calculate and report the mean and median total number of steps taken per day
meanSteps <- mean(totalSteps$steps)
meanSteps

medianSteps <- median(totalSteps$steps)
medianSteps

# Report Answer:
# mean: 10766.19
# median: 10765

```
# What is the average daily activity pattern?
```
# 1. Make a time series plot (i.e. type = "l") of the 5-minute interval (x-axis) and the average number of steps taken, averaged across all days (y-axis)
stepsInterval <- aggregate(steps ~ interval, data = activityData, mean, na.rm = T)
plot(steps ~ interval, data = stepsInterval, type = "l", 
     main = "Average number of steps taken at 5 minute intervals",
     xlab = "Time Intervals(5-minute)", 
     ylab = "Mean Number of Steps taken (all days)")

# 2. Which 5-minute interval, on average across all the days in the dataset, contains the maximum number of steps?
maxStepInterval <- stepsInterval[which.max(stepsInterval$steps), "interval"]
maxStepInterval

# Report Answer:
# maximum number of steps: 835

```
# Imputing missing values
```
# 1. Calculate and report the total number of missing values in the dataset (i.e. the total number of rows with NAs)
missingData <- sum(!complete.cases(activityData))
missingData

# Report Answer:
# total of missing data: 2304

# 2. Devise a strategy for filling in all of the missing values in the dataset.
getStepsPerinterval <- function(interval){
  stepsInterval[stepsInterval$interval == interval, "steps"]
}

# 3. Create a new dataset that is equal to the original dataset but with the missing data filled in.
fullAct <- activityData

flag = 0
for(i in 1:nrow(fullAct)){
  if(is.na(fullAct[i, "steps"])){
    fullAct[i, "steps"] <- getStepsPerinterval(fullAct[i, "interval"])
    flag = flag + 1
  }
}

flag

# 4. Make a histogram of the total number of steps taken each day and Calculate and report the mean and median total number of steps taken per day.
newTotalStepsPerDays <- aggregate(steps ~ date, data = fullAct, sum)
hist(newTotalStepsPerDays$steps, 
     main = "Histogram of total number of steps taken each day",
     xlab = "Total number of steps", 
     ylab = "Frequency")

meanNewData <- mean(newTotalStepsPerDays$steps)
meanNewData

medianNewData <- median(newTotalStepsPerDays$steps)
medianNewData

# Report Answer:
# new mean: 10766.19
# new median: 10766.19

# old and new mean remain the same
# old and new mean not the same, where new median number slightly higer a bit 

```
# Are there differences in activity patterns between weekdays and weekends?
```
# 1. Create a new factor variable in the dataset with two levels -- "weekday" and "weekend" indicating whether a given date is a weekday or weekend day.
weekData <- activityData 
weekData$day <- ifelse(as.POSIXlt(as.Date(weekData$date))$wday%%6
                       == 0, "weekend", "weekday")
weekData$day <- factor(weekData$day, levels = c("weekday", "weekend"))

interval <- aggregate(steps ~ interval + day, weekData, mean)

# 2. Make a panel plot containing a time series plot (i.e. type = "l") of the 5-minute interval (x-axis) and the average number of steps taken, averaged across all weekday days or weekend days (y-axis). 
library(lattice)
xyplot(steps ~ interval | day, data = interval, layout = c(1, 2), type = "l", 
       main = "Weekend vs Avg Steps",
       xlab = "Interval(Steps)", 
       ylab = "Average Steps")

```







